version: '3.9'

x-app-args: &app-args
  - USER=${USER}
  - UID=${UID}


#x-app-logging: &app-logging
#  driver: "json-file"
#  options:
#    max-size: "12Mb"
#    max-file: "1"
#
volumes:
  mysql-db-data:
#  mongo-db-data:
#  elastic-data:
#  kibana-data:
#  rabbitmq-data:
#
#networks:
#  default:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 11.14.0.0/16
#  traefik-net:
#    name: traefik_net
#    external: true
services:
  #
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./etc/nginx:/etc/nginx/conf.d
      - ./src/back:/var/www
    depends_on:
      - back
  #
  back:
    build:
      context: ./images/php
      dockerfile: Dockerfile
      args: *app-args
    depends_on:
      - mysql
    volumes:
      - ./src/back:/var/www
  #
  mysql:
    image: mysql:8.0
    ports:
      - ${LOCAL_FORWARD_MYSQL_DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${LOCAL_MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-p${LOCAL_MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 20
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - mysql-db-data:/var/lib/mysql
  #
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.3
    environment:
      - PMA_HOST=mysql
      - PMA_ABSOLUTE_URI=http://localhost/pma/
      - MYSQL_ROOT_PASSWORD=${LOCAL_MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_USER=${LOCAL_MYSQL_USER:-user}
      - MYSQL_PASSWORD=${LOCAL_MYSQL_USER_PASSWORD:-pass}
      - UPLOAD_LIMIT=100000000
    depends_on:
      - mysql